/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-09 at 20:21:34 UTC 
 * Modify at your own risk.
 */

package com.appspot.quotesbookapp.quotesclient.model;

/**
 * Model definition for ApiMessagesSearchRequestMsg.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the quotesclient. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApiMessagesSearchRequestMsg extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("n_page") @com.google.api.client.json.JsonString
  private java.lang.Long nPage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("page_size") @com.google.api.client.json.JsonString
  private java.lang.Long pageSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("text_query")
  private java.lang.String textQuery;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNPage() {
    return nPage;
  }

  /**
   * @param nPage nPage or {@code null} for none
   */
  public ApiMessagesSearchRequestMsg setNPage(java.lang.Long nPage) {
    this.nPage = nPage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPageSize() {
    return pageSize;
  }

  /**
   * @param pageSize pageSize or {@code null} for none
   */
  public ApiMessagesSearchRequestMsg setPageSize(java.lang.Long pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTextQuery() {
    return textQuery;
  }

  /**
   * @param textQuery textQuery or {@code null} for none
   */
  public ApiMessagesSearchRequestMsg setTextQuery(java.lang.String textQuery) {
    this.textQuery = textQuery;
    return this;
  }

  @Override
  public ApiMessagesSearchRequestMsg set(String fieldName, Object value) {
    return (ApiMessagesSearchRequestMsg) super.set(fieldName, value);
  }

  @Override
  public ApiMessagesSearchRequestMsg clone() {
    return (ApiMessagesSearchRequestMsg) super.clone();
  }

}
