/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-09 at 20:21:34 UTC 
 * Modify at your own risk.
 */

package com.appspot.quotesbookapp.quotesclient.model;

/**
 * Model definition for ApiMessagesSearchResultMsg.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the quotesclient. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApiMessagesSearchResultMsg extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("n_page") @com.google.api.client.json.JsonString
  private java.lang.Long nPage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("page_quotes")
  private java.util.List<ApiMessagesQuoteMsg> pageQuotes;

  static {
    // hack to force ProGuard to consider ApiMessagesQuoteMsg used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(ApiMessagesQuoteMsg.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("page_size") @com.google.api.client.json.JsonString
  private java.lang.Long pageSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String query;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("total_pages") @com.google.api.client.json.JsonString
  private java.lang.Long totalPages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("total_results") @com.google.api.client.json.JsonString
  private java.lang.Long totalResults;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNPage() {
    return nPage;
  }

  /**
   * @param nPage nPage or {@code null} for none
   */
  public ApiMessagesSearchResultMsg setNPage(java.lang.Long nPage) {
    this.nPage = nPage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ApiMessagesQuoteMsg> getPageQuotes() {
    return pageQuotes;
  }

  /**
   * @param pageQuotes pageQuotes or {@code null} for none
   */
  public ApiMessagesSearchResultMsg setPageQuotes(java.util.List<ApiMessagesQuoteMsg> pageQuotes) {
    this.pageQuotes = pageQuotes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPageSize() {
    return pageSize;
  }

  /**
   * @param pageSize pageSize or {@code null} for none
   */
  public ApiMessagesSearchResultMsg setPageSize(java.lang.Long pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQuery() {
    return query;
  }

  /**
   * @param query query or {@code null} for none
   */
  public ApiMessagesSearchResultMsg setQuery(java.lang.String query) {
    this.query = query;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTotalPages() {
    return totalPages;
  }

  /**
   * @param totalPages totalPages or {@code null} for none
   */
  public ApiMessagesSearchResultMsg setTotalPages(java.lang.Long totalPages) {
    this.totalPages = totalPages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTotalResults() {
    return totalResults;
  }

  /**
   * @param totalResults totalResults or {@code null} for none
   */
  public ApiMessagesSearchResultMsg setTotalResults(java.lang.Long totalResults) {
    this.totalResults = totalResults;
    return this;
  }

  @Override
  public ApiMessagesSearchResultMsg set(String fieldName, Object value) {
    return (ApiMessagesSearchResultMsg) super.set(fieldName, value);
  }

  @Override
  public ApiMessagesSearchResultMsg clone() {
    return (ApiMessagesSearchResultMsg) super.clone();
  }

}
