/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-05-05 20:00:12 UTC)
 * on 2015-05-10 at 23:25:48 UTC 
 * Modify at your own risk.
 */

package com.appspot.quotesbookapp.quotesclient.model;

/**
 * Model definition for ApiMessagesAuthorMsg.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the quotesclient. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApiMessagesAuthorMsg extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String biography;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("first_name")
  private java.lang.String firstName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("last_name")
  private java.lang.String lastName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("picture_url")
  private java.lang.String pictureUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("short_description")
  private java.lang.String shortDescription;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBiography() {
    return biography;
  }

  /**
   * @param biography biography or {@code null} for none
   */
  public ApiMessagesAuthorMsg setBiography(java.lang.String biography) {
    this.biography = biography;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFirstName() {
    return firstName;
  }

  /**
   * @param firstName firstName or {@code null} for none
   */
  public ApiMessagesAuthorMsg setFirstName(java.lang.String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLastName() {
    return lastName;
  }

  /**
   * @param lastName lastName or {@code null} for none
   */
  public ApiMessagesAuthorMsg setLastName(java.lang.String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPictureUrl() {
    return pictureUrl;
  }

  /**
   * @param pictureUrl pictureUrl or {@code null} for none
   */
  public ApiMessagesAuthorMsg setPictureUrl(java.lang.String pictureUrl) {
    this.pictureUrl = pictureUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getShortDescription() {
    return shortDescription;
  }

  /**
   * @param shortDescription shortDescription or {@code null} for none
   */
  public ApiMessagesAuthorMsg setShortDescription(java.lang.String shortDescription) {
    this.shortDescription = shortDescription;
    return this;
  }

  @Override
  public ApiMessagesAuthorMsg set(String fieldName, Object value) {
    return (ApiMessagesAuthorMsg) super.set(fieldName, value);
  }

  @Override
  public ApiMessagesAuthorMsg clone() {
    return (ApiMessagesAuthorMsg) super.clone();
  }

}
